version: '3.7'
services:

  frontend:
    image: jitrak/docker-compose-demo-frontend:1.0.0
    restart: always
    environment:
      - API_URL=http://localhost:3000/api/v1
    ports:
      - 80:80
    networks: 
      - frontend

  backend:
    image: jitrak/docker-compose-demo-backend:1.0.0
    restart: always
    depends_on:
      - mongo
    environment:
      PORT: 3000
      MONGO_URL: mongodb://root:myPassword@mongo:27017
      DB_NAME: world
    ports:
      - 3000:3000
    networks: 
      - backend
    
  mongo:
    image: mongo:7.0.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: myPassword
      MONGO_INITDB_DATABASE: world
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d/:ro
      - ./db/init-data/:/tmp/init-data/:ro
      - db-data-prod:/data/db
    networks: 
      - backend

  mongo-express:
    image: mongo-express:1.0.0-20-alpine3.18
    restart: always
    depends_on:
      - mongo
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: born2dev
      ME_CONFIG_BASICAUTH_PASSWORD: ved2nrob
      ME_CONFIG_MONGODB_URL: mongodb://root:myPassword@mongo:27017/
    networks: 
      - backend

volumes:
  db-data-prod:

networks:
  frontend:
  backend:
