services:
  mongo:
    image: mongo:7.0.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: myPassword
      MONGO_INITDB_DATABASE: world
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d/:ro
      - ./db/init-data/:/tmp/init-data/:ro
      - db-data:/data/db
    networks: 
      - database

  mongo-express:
    image: mongo-express:1.0.0-20-alpine3.18
    restart: always
    depends_on:
      - mongo
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: born2dev
      ME_CONFIG_BASICAUTH_PASSWORD: ved2nrob
      ME_CONFIG_MONGODB_URL: mongodb://root:myPassword@mongo:27017/
    networks: 
      - database

volumes:
  db-data:

networks:
  database:
